apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
spec:
  description: k8s infra deployments
  destinations:
    - namespace: 'management'
      server: '*'
    - namespace: 'monitoring'
      server: '*'
    - namespace: 'infra'
      server: '*'
    - namespace: 'traefik'
      server: '*'
    - namespace: 'argocd'
      server: '*'
  sourceRepos:
    - '*'
